name: steemdart_ecc
description: Elliptic curve cryptography functions in Dart. Private Key, Public Key, Signature, AES, Encryption, Decryption
version: 0.4.4+0
homepage: https://github.com/anpigon/steemdart_ecc

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bs58check: ^1.0.2
  pointycastle: ^3.0.1
  crypto: ^3.0.1
  convert: ^3.0.0
  http: ^1.1.0
  json_annotation: ^4.0.1
  buffer: ^1.1.1

dev_dependencies:
  test: ^1.18.1
  dotenv: ^4.2.0
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  json_serializable: ^6.7.1
  analyzer: ^6.3.0
  data_faker: ^0.0.5
