// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'account.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Authority _$AuthorityFromJson(Map<String, dynamic> json) {
  return Authority(
    weight_threshold: json['weight_threshold'] as int,
    account_auths: json['account_auths'] as List<dynamic>,
    key_auths: json['key_auths'] as List<dynamic>,
  );
}

Map<String, dynamic> _$AuthorityToJson(Authority instance) => <String, dynamic>{
      'weight_threshold': instance.weight_threshold,
      'account_auths': instance.account_auths,
      'key_auths': instance.key_auths,
    };

Account _$AccountFromJson(Map<String, dynamic> json) {
  return Account(
    id: json['id'] as int,
    name: json['name'] as String,
    owner: Authority.fromJson(json['owner'] as Map<String, dynamic>),
    active: Authority.fromJson(json['active'] as Map<String, dynamic>),
    posting: Authority.fromJson(json['posting'] as Map<String, dynamic>),
    memo_key: json['memo_key'] as String,
    json_metadata: json['json_metadata'] as String,
    proxy: json['proxy'] as String,
    last_owner_update: json['last_owner_update'] as String,
    last_account_update: json['last_account_update'] as String,
    created: json['created'] as String,
    mined: json['mined'] as bool,
    recovery_account: json['recovery_account'] as String,
    last_account_recovery: json['last_account_recovery'] as String,
    reset_account: json['reset_account'] as String,
    comment_count: json['comment_count'] as int,
    lifetime_vote_count: json['lifetime_vote_count'] as int,
    post_count: json['post_count'] as int,
    can_vote: json['can_vote'] as bool,
    voting_power: json['voting_power'] as int,
    last_vote_time: json['last_vote_time'] as String,
    balance: json['balance'] as String,
    savings_balance: json['savings_balance'] as String,
    sbd_balance: json['sbd_balance'] as String,
    sbd_seconds: json['sbd_seconds'] as String,
    sbd_seconds_last_update: json['sbd_seconds_last_update'] as String,
    sbd_last_interest_payment: json['sbd_last_interest_payment'] as String,
    savings_sbd_balance: json['savings_sbd_balance'] as String,
    savings_sbd_seconds: json['savings_sbd_seconds'] as String,
    savings_sbd_seconds_last_update:
        json['savings_sbd_seconds_last_update'] as String,
    savings_sbd_last_interest_payment:
        json['savings_sbd_last_interest_payment'] as String,
    savings_withdraw_requests: json['savings_withdraw_requests'] as int,
    reward_sbd_balance: json['reward_sbd_balance'] as String,
    reward_steem_balance: json['reward_steem_balance'] as String,
    reward_vesting_balance: json['reward_vesting_balance'] as String,
    reward_vesting_steem: json['reward_vesting_steem'] as String,
    vesting_shares: json['vesting_shares'] as String,
    delegated_vesting_shares: json['delegated_vesting_shares'] as String,
    received_vesting_shares: json['received_vesting_shares'] as String,
    vesting_withdraw_rate: json['vesting_withdraw_rate'] as String,
    next_vesting_withdrawal: json['next_vesting_withdrawal'] as String,
    withdrawn: json['withdrawn'],
    to_withdraw: json['to_withdraw'],
    withdraw_routes: json['withdraw_routes'] as int,
    curation_rewards: json['curation_rewards'] as int,
    posting_rewards: json['posting_rewards'] as int,
    proxied_vsf_votes: json['proxied_vsf_votes'] as List<dynamic>,
    witnesses_voted_for: json['witnesses_voted_for'] as int,
    last_post: json['last_post'] as String,
    last_root_post: json['last_root_post'] as String,
    vesting_balance: json['vesting_balance'] as String,
    reputation: json['reputation'],
    transfer_history: json['transfer_history'] as List<dynamic>,
    market_history: json['market_history'] as List<dynamic>,
    post_history: json['post_history'] as List<dynamic>,
    vote_history: json['vote_history'] as List<dynamic>,
    other_history: json['other_history'] as List<dynamic>,
    witness_votes: json['witness_votes'] as List<dynamic>,
    tags_usage: json['tags_usage'] as List<dynamic>,
    guest_bloggers: json['guest_bloggers'] as List<dynamic>,
    voting_manabar:
        RCManabar.fromJson(json['voting_manabar'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$AccountToJson(Account instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'owner': instance.owner,
      'active': instance.active,
      'posting': instance.posting,
      'memo_key': instance.memo_key,
      'json_metadata': instance.json_metadata,
      'proxy': instance.proxy,
      'last_owner_update': instance.last_owner_update,
      'last_account_update': instance.last_account_update,
      'created': instance.created,
      'mined': instance.mined,
      'recovery_account': instance.recovery_account,
      'last_account_recovery': instance.last_account_recovery,
      'reset_account': instance.reset_account,
      'comment_count': instance.comment_count,
      'lifetime_vote_count': instance.lifetime_vote_count,
      'post_count': instance.post_count,
      'can_vote': instance.can_vote,
      'voting_power': instance.voting_power,
      'last_vote_time': instance.last_vote_time,
      'balance': instance.balance,
      'savings_balance': instance.savings_balance,
      'sbd_balance': instance.sbd_balance,
      'sbd_seconds': instance.sbd_seconds,
      'sbd_seconds_last_update': instance.sbd_seconds_last_update,
      'sbd_last_interest_payment': instance.sbd_last_interest_payment,
      'savings_sbd_balance': instance.savings_sbd_balance,
      'savings_sbd_seconds': instance.savings_sbd_seconds,
      'savings_sbd_seconds_last_update':
          instance.savings_sbd_seconds_last_update,
      'savings_sbd_last_interest_payment':
          instance.savings_sbd_last_interest_payment,
      'savings_withdraw_requests': instance.savings_withdraw_requests,
      'reward_sbd_balance': instance.reward_sbd_balance,
      'reward_steem_balance': instance.reward_steem_balance,
      'reward_vesting_balance': instance.reward_vesting_balance,
      'reward_vesting_steem': instance.reward_vesting_steem,
      'vesting_shares': instance.vesting_shares,
      'delegated_vesting_shares': instance.delegated_vesting_shares,
      'received_vesting_shares': instance.received_vesting_shares,
      'vesting_withdraw_rate': instance.vesting_withdraw_rate,
      'next_vesting_withdrawal': instance.next_vesting_withdrawal,
      'withdrawn': instance.withdrawn,
      'to_withdraw': instance.to_withdraw,
      'withdraw_routes': instance.withdraw_routes,
      'curation_rewards': instance.curation_rewards,
      'posting_rewards': instance.posting_rewards,
      'proxied_vsf_votes': instance.proxied_vsf_votes,
      'witnesses_voted_for': instance.witnesses_voted_for,
      'last_post': instance.last_post,
      'last_root_post': instance.last_root_post,
      'vesting_balance': instance.vesting_balance,
      'reputation': instance.reputation,
      'transfer_history': instance.transfer_history,
      'market_history': instance.market_history,
      'post_history': instance.post_history,
      'vote_history': instance.vote_history,
      'other_history': instance.other_history,
      'witness_votes': instance.witness_votes,
      'tags_usage': instance.tags_usage,
      'guest_bloggers': instance.guest_bloggers,
      'voting_manabar': instance.voting_manabar,
    };
